services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    networks:
      - e-learning-network

  sqlserver-express:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: "sqlserver-express"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Rot@2112002
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      e-learning-network:
        aliases:
          - "localhost\\SQLEXPRESS"

volumes:
  sqlserverdata:

networks:
  e-learning-network:
    external: true
