version: '3.8'

services:
  user-management-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      # Dummy connection string for dev/test — avoid actual DB dependency
      - ConnectionStrings__DefaultConnection=Server=dummy;Database=dummy;User Id=dummy;Password=dummy;
    restart: always
